# Generated by Django 2.2.3 on 2019-07-21 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20190721_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='Aadharno',
            field=models.CharField(default=' ', max_length=12),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Voteridno',
            field=models.CharField(default=' ', max_length=12),
        ),
    ]
